# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('congregacao', models.CharField(max_length=100, verbose_name='Congregação')),
                ('tema', models.CharField(max_length=100, verbose_name='Tema')),
                ('email', models.EmailField(max_length=254)),
                ('dia', models.CharField(max_length=100, verbose_name='Dia')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('ajuda', models.CharField(choices=[('---', '---'), ('Sim', 'Sim'), ('Não', 'Não')], max_length=100, verbose_name='Ajuda')),
                ('custo', models.CharField(max_length=100, verbose_name='Custo')),
                ('nota', models.CharField(choices=[('---', '---'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100, verbose_name='Nota')),
            ],
        ),
    ]
