version: '3'

services: 
  django:
    build:
      dockerfile: ./docker/dockerfile
      context: .
    image: iesodias/pythondjango
    volumes:
      - .:/code
    container_name: DjangoServer
    ports: 
      - "8000:8000"
    networks: 
      - network1
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - network1

networks: 
  network1:
    driver: bridge