FROM python:3.6
ENV PYTHONUNBUFFERED 1
MAINTAINER Ieso Dias
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install -r ./requirements.txt
ENTRYPOINT [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]
EXPOSE 8000

 