# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temas',
            options={'verbose_name': 'tema', 'verbose_name_plural': 'temas'},
        ),
    ]
