# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('sexo', models.CharField(max_length=30, verbose_name='sexo')),
                ('designacao', models.CharField(max_length=30, verbose_name='designacao')),
                ('carrinho', models.CharField(max_length=30, verbose_name='carrinho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
